server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~ /\. {
        deny all;
    }
    location = /docker-compose.yml {
        deny all;
    }
    location = /nginx.conf {
        deny all;
    }
}
